### ISSUE TITLE
ガイドラインを日本語に翻訳する

### ISSUE THREAD

**Issue by takayukister** [jawordpressorg/support-forum-admin#1]
WordPress サポートフォーラムガイドラインには度々改訂が行われていますが最近行われた改訂はいつもより大きなものだったようです。

https://wordpress.org/support/guidelines/

この英語原文を日本語に翻訳し、下記リンクのページ内容を更新します。

https://ja.wordpress.org/support/article/guidelines/

注意事項
* 日本語訳は[翻訳スタイルガイド](https://ja.wordpress.org/team/handbook/translation/translation-style-guide/)に従った体裁に仕上げてください。
* 翻訳はガイドラインの条項ごとにまとめてプルリクエストの形式で提案してください。

**Comment by takayukister** [comment]
[forum-guidelines.md](https://github.com/jawordpressorg/support-forum-admin/blob/main/forum-guidelines.md) に原文を置きますのでこちらにプルリクください。

**Comment by YukinobuAsakawa** [comment]
ガイドラインを日本語に翻訳する #1 にぜひ参加させてください。

以下、私の自己紹介になります。

- 名前: 浅川幸宣（あさかわゆきのぶ）
- 職業: システムエンジニア（フリーランス）
- WordPress歴: 8年程度
- WordPress.orgプロフィールページ: https://profiles.wordpress.org/yukinobu/
- これまでのコミュニティでの活動: 翻訳やドキュメント整備、サポートフォーラムでの回答など
- 今後やってみたいこと: コア開発への貢献、サポートフォーラムでの活動を増やす。

**Comment by takayukister** [comment]
メモ: ガイドラインに更新がありました。

https://make.wordpress.org/support/2024/02/guideline-change-reviews-of-commercial-pro-plugins/

**Comment by takayukister** [comment]
注意: main ブランチに[保護設定](https://docs.github.com/ja/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches)をしていますので main に直接コミットすることができないようになっています。フォークしたリポジトリに適当な名前("draft" とか)のブランチを作ってそこに一度コミットして main にプルリクするようにしてみてください。

**Comment by takayukister** [comment]
https://ja.wordpress.org/support/article/guidelines/ に反映しました。
